name: investigation_process_mobile
version: 0.4.5+45
publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.3.2
  pdf: ^3.11.1
  printing: ^5.13.4
  intl: any
  path_provider: ^2.1.5
  share_plus: ^10.0.2
  http: ^1.2.2

  speech_to_text: ^7.4.0
flutter:
  uses-material-design: true
